#spring:
#  datasource:
#  url: jdbc:postgresql://localhost:5432//shortened_url
#  username: postgres
#  password: postgres
#
#  jpa:
#    hibernate:
#    # ddl-auto: update
#    ddl-auto: none
#    show-sql: true
#    properties:
#  hibernate:
#    format_sql: false
#
#    output:
#    ansi:
#    enabled: ALWAYS
#
#  flyway:
#    check-location: false